spring:
  # thymeleaf
  thymeleaf:
    # ??????
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/seckill?useUnicode=true&&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
      # ???????
      pool-name: DateHikariCP
      # ??ะก??????????
      minimum-idle: 5
      # ???????????????????600000??10?????
      idle-timeout: 18000
      # ??????????????10
      maximum-pool-size: 10
      # ?????????????????????
      auto-commit: true
      # ????????????0????????????1800000??30?????
      max-lifetime: 18000
      # ????????????30000??30??
      connection-timeout: 3000
      # ????????????????????
      connection-test-query: SELECT 1

mybatis-plus:
  # ????Mapper??????
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # ????MyBatis??????????????????????????????
  type-aliases-package: com.zheng.seckilledu.pojo

logging:
  level:
    com.zheng.seckilledu.mapper: debug
